#!/bin/bash

faces="Arjun"
styles=(Regular Bold Italic)
desc_long="Pan Gurmukhi font designed to support all the languages using the Gurmukhi script."

export nlci=$HOME/script/tools
source ${nlci}/prepare.bash

source ${nlci}/addchars.bash

source ${nlci}/metadata.bash
echo "done producing UFO sources"
