#!/bin/bash

faces=(Arjun)
styles=(Regular Bold Italic)
desc_long="Gurmukhi script font for all languages using the Gurmukhi script"

export nlci=$HOME/script/tools
export src=source
source ${nlci}/prepare.bash

source ${nlci}/metadata.bash

rm -f ${src}/*-???*.sfd*
echo "done producing UFO sources"
